# Generated by Django 5.2.8 on 2025-12-11 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.SlugField(max_length=200, unique=True, verbose_name='ID Plante')),
                ('scientific_name', models.CharField(max_length=200, verbose_name='Nom scientifique')),
                ('common_name_fr', models.CharField(max_length=200, verbose_name='Nom commun (FR)')),
                ('common_names_local', models.JSONField(blank=True, default=list, verbose_name='Noms locaux')),
                ('family', models.CharField(max_length=100, verbose_name='Famille')),
                ('genus', models.CharField(max_length=100, verbose_name='Genre')),
                ('species', models.CharField(max_length=100, verbose_name='Espèce')),
                ('description', models.TextField(verbose_name='Description')),
                ('plant_type', models.CharField(choices=[('arbre', 'Arbre'), ('arbuste', 'Arbuste'), ('herbe', 'Herbe'), ('liane', 'Liane'), ('autre', 'Autre')], max_length=20, verbose_name='Type de plante')),
                ('parts_used', models.JSONField(default=list, verbose_name='Parties utilisées')),
                ('regions', models.JSONField(blank=True, default=list, verbose_name='Régions')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='Images')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Plante',
                'verbose_name_plural': 'Plantes',
                'ordering': ['scientific_name'],
            },
        ),
        migrations.CreateModel(
            name='MedicinalProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=200, verbose_name='Type de propriété')),
                ('description', models.TextField(verbose_name='Description')),
                ('evidence_level', models.CharField(choices=[('traditionnel', 'Traditionnel'), ('preliminaire', 'Préliminaire'), ('clinique', 'Clinique')], default='traditionnel', max_length=20, verbose_name='Niveau de preuve')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicinal_properties', to='plants.plant', verbose_name='Plante')),
            ],
            options={
                'verbose_name': 'Propriété médicinale',
                'verbose_name_plural': 'Propriétés médicinales',
                'ordering': ['property_type'],
            },
        ),
        migrations.CreateModel(
            name='TraditionalUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indication', models.CharField(max_length=300, verbose_name='Indication')),
                ('preparation', models.TextField(verbose_name='Préparation')),
                ('recipe', models.TextField(blank=True, verbose_name='Recette')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Région')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traditional_uses', to='plants.plant', verbose_name='Plante')),
            ],
            options={
                'verbose_name': 'Usage traditionnel',
                'verbose_name_plural': 'Usages traditionnels',
                'ordering': ['indication'],
            },
        ),
    ]
