# Generated by Django 5.2.8 on 2025-12-11 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='ID Session')),
                ('image_hash', models.CharField(db_index=True, max_length=64, verbose_name="Hash de l'image")),
                ('image_path', models.CharField(blank=True, max_length=500, null=True, verbose_name="Chemin de l'image")),
                ('predicted_confidence', models.FloatField(verbose_name='Confiance prédite (%)')),
                ('alternatives', models.JSONField(blank=True, default=list, verbose_name='Alternatives')),
                ('feedback_type', models.CharField(choices=[('rating', 'Note'), ('correction', 'Correction'), ('comment', 'Commentaire'), ('confirmation', 'Confirmation')], max_length=20, verbose_name='Type de feedback')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Note (1-5)')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Prédiction correcte')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('user_intent', models.CharField(blank=True, max_length=50, null=True, verbose_name='Intention utilisateur')),
                ('device_info', models.JSONField(blank=True, default=dict, verbose_name='Informations appareil')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('used', 'Utilisé')], default='pending', max_length=20, verbose_name='Statut')),
                ('curator_notes', models.TextField(blank=True, verbose_name='Notes du curateur')),
                ('curated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de curation')),
                ('correct_plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correct_feedbacks', to='plants.plant', verbose_name='Plante correcte')),
                ('curated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Curateur')),
                ('predicted_plant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_feedbacks', to='plants.plant', verbose_name='Plante prédite')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Feedback de prédiction',
                'verbose_name_plural': 'Feedbacks de prédiction',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['image_hash', 'status'], name='feedback_pr_image_h_0f7817_idx'), models.Index(fields=['status', '-timestamp'], name='feedback_pr_status_a7abab_idx')],
            },
        ),
    ]
